Module 9
kjnvarma/DevOps-Course-Starter pull request #12
Opened 2021-04-21 14:53 UTC by kjnvarma

module 9

2021-04-26 12:03 UTC, hugh-emerson requested changes
Pretty good. I've left some suggestions but the only important point is that your pipeline is currently broken. Check that it passes and that it can successfully deploy to Heroku.

2021-04-26 12:03 UTC, hugh-emerson commented on .env.test
> +TRELLO_DONE_LIST_ID='Test'
You should be able to get rid of any reference to Trello

2021-04-26 12:03 UTC, hugh-emerson commented on .travis.yml
> +  - docker build --target production --tag $DOCKER_HUB_USER/todo-app:latest .
You mean `DOCKER_USER`, not `DOCKER_HUB_USER`

This is causing your pipeline to fail

2021-04-26 12:03 UTC, hugh-emerson commented on Dockerfile
> +ENTRYPOINT ["poetry", "run", "flask run -h 0.0.0.0 -p 5000"]
Should be `... "flask", "run", "-h", "...` etc

2021-04-26 12:03 UTC, hugh-emerson commented on run.sh
> +poetry install
You already have `RUN poetry install` on line 22 of your Dockerfile, so installing it again shouldn't be necessary.

However Heroku is a bit funny about it, so the best setup is to not use a virtual env. You could change line 22 to:
```
RUN poetry config virtualenvs.create false --local && poetry install --no-dev --no-root
```
And then remove "poetry install" from this file. Installing things globally is fine within the container since it's already isolated. And `--no-dev` will skip things like pytest which aren't necessary for the production image.

2021-04-26 12:03 UTC, hugh-emerson commented on todo_app/mongo_db_tasks.py
> +}
Unused

2021-04-26 12:03 UTC, hugh-emerson commented on todo_app/mongo_db_tasks.py
> +def get_db_name():
All of these functions are repeated inside the TasksDb class.

2021-04-26 12:03 UTC, hugh-emerson commented on todo_app/mongo_db_tasks.py
> +            db_name = "Board"
```suggestion
        db_name = os.getenv('MONGO_DB_NAME', 'Board')
```

2021-04-26 12:03 UTC, hugh-emerson commented on todo_app/mongo_db_tasks.py
> +            tasks_table_name = "Tasks"
Table/collection names aren't normally environment specific. Different environments could have different databases and then use the same names for tables/collections

2021-04-26 12:03 UTC, hugh-emerson commented on todo_app/test_system.py
> +    file_path = dotenv.find_dotenv('.env')
You're missing `dotenv.load_dotenv(file_path, override=True)`

2021-04-26 12:03 UTC, hugh-emerson commented on todo_app/test_system.py
> +    application = app.create_app(db)
You're using the real database? Automated tests should have their own database. Or given that you have made the collection name configurable, you could at least have set a different value for that.

2021-04-26 12:03 UTC, hugh-emerson commented on todo_app/test_system.py
> +        db.delete_task(id)
This is a bit fragile/doesn't scale:
It depends on "TestItem" staying in sync with any tests. What if there are tests that set up multiple items?

2021-05-26 16:08 UTC, kjnvarma commented
Module 9 merges

2021-05-26 16:08 UTC, merged

2021-06-01 14:53 UTC, JackMead commented
Thanks for fixing up your Travis build, I can see that this was tested, built & deployed successfully so I'm happy that it's merged